// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package bank

import "strconv"

type BankAction byte

const (
	BankActionPLUS   BankAction = 0
	BankActionMINUS  BankAction = 1
	BankActionCOMMIT BankAction = 2
)

var EnumNamesBankAction = map[BankAction]string{
	BankActionPLUS:   "PLUS",
	BankActionMINUS:  "MINUS",
	BankActionCOMMIT: "COMMIT",
}

var EnumValuesBankAction = map[string]BankAction{
	"PLUS":   BankActionPLUS,
	"MINUS":  BankActionMINUS,
	"COMMIT": BankActionCOMMIT,
}

func (v BankAction) String() string {
	if s, ok := EnumNamesBankAction[v]; ok {
		return s
	}
	return "BankAction(" + strconv.FormatInt(int64(v), 10) + ")"
}
