// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package transaction

import "strconv"

type TransactionType int8

const (
	/// Legacy transaction type.
	TransactionTypeLegacy  TransactionType = 0
	/// EIP-2930 Access List transaction type.
	TransactionTypeEip2930 TransactionType = 1
	/// EIP-1559 Fee market change transaction type.
	TransactionTypeEip1559 TransactionType = 2
	/// EIP-4844 Blob transaction type.
	TransactionTypeEip4844 TransactionType = 3
	/// EIP-7702 Set EOA account code transaction type.
	TransactionTypeEip7702 TransactionType = 4
	/// Custom type means that transaction trait was extend and have custom types.
	TransactionTypeCustom  TransactionType = 5
)

var EnumNamesTransactionType = map[TransactionType]string{
	TransactionTypeLegacy:  "Legacy",
	TransactionTypeEip2930: "Eip2930",
	TransactionTypeEip1559: "Eip1559",
	TransactionTypeEip4844: "Eip4844",
	TransactionTypeEip7702: "Eip7702",
	TransactionTypeCustom:  "Custom",
}

var EnumValuesTransactionType = map[string]TransactionType{
	"Legacy":  TransactionTypeLegacy,
	"Eip2930": TransactionTypeEip2930,
	"Eip1559": TransactionTypeEip1559,
	"Eip4844": TransactionTypeEip4844,
	"Eip7702": TransactionTypeEip7702,
	"Custom":  TransactionTypeCustom,
}

func (v TransactionType) String() string {
	if s, ok := EnumNamesTransactionType[v]; ok {
		return s
	}
	return "TransactionType(" + strconv.FormatInt(int64(v), 10) + ")"
}
