// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package account

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AccountRecord struct {
	_tab flatbuffers.Table
}

func GetRootAsAccountRecord(buf []byte, offset flatbuffers.UOffsetT) *AccountRecord {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AccountRecord{}
	x.Init(buf, n+offset)
	return x
}

func FinishAccountRecordBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAccountRecord(buf []byte, offset flatbuffers.UOffsetT) *AccountRecord {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AccountRecord{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAccountRecordBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AccountRecord) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AccountRecord) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AccountRecord) Address(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *AccountRecord) AddressLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *AccountRecord) AddressBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AccountRecord) MutateAddress(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *AccountRecord) Sequence() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AccountRecord) MutateSequence(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func AccountRecordStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func AccountRecordAddAddress(builder *flatbuffers.Builder, address flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(address), 0)
}
func AccountRecordStartAddressVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func AccountRecordAddSequence(builder *flatbuffers.Builder, sequence uint64) {
	builder.PrependUint64Slot(1, sequence, 0)
}
func AccountRecordEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
