// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package account

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AccountRecords struct {
	_tab flatbuffers.Table
}

func GetRootAsAccountRecords(buf []byte, offset flatbuffers.UOffsetT) *AccountRecords {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AccountRecords{}
	x.Init(buf, n+offset)
	return x
}

func FinishAccountRecordsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAccountRecords(buf []byte, offset flatbuffers.UOffsetT) *AccountRecords {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AccountRecords{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAccountRecordsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AccountRecords) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AccountRecords) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AccountRecords) Records(obj *AccountRecord, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *AccountRecords) RecordsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func AccountRecordsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func AccountRecordsAddRecords(builder *flatbuffers.Builder, records flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(records), 0)
}
func AccountRecordsStartRecordsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func AccountRecordsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
