name: Build rust librevmapi
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "release/*"
    paths:
      - "crates/**"
      - "librevm/**"
      - "Cargo.toml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux-glibc:
    name: Linux glibc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: make release-build-linux

      - uses: actions/upload-artifact@v4
        with:
          name: librevmapi-linux-glibc
          path: core/*.so

  build-macos:
    name: MacOS glibc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: make release-build-macos

      - uses: actions/upload-artifact@v4
        with:
          name: librevmapi-macos
          path: core/*.dylib

  commit:
    name: Commit shared libraries
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    needs: [build-linux-glibc, build-macos]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
      - name: Get linux-glibc artifacts
        uses: actions/download-artifact@v4
        with:
          name: librevmapi-linux-glibc
          path: api

      - name: Get macos artifacts
        uses: actions/download-artifact@v4
        with:
          name: librevmapi-macos
          path: api

      - name: Commit shared libraries
        uses: EndBug/add-and-commit@v9
        with:
          add: '["core/librevmapi.dylib", "core/librevmapi.aarch64.so", "core/librevmapi.x86_64.so" ]'
          default_author: github_actions
          message: "update shared libraries"
